require:
  - rubocop/cop/rubocop_rails_accessibility_cops

AllCops:
  DisabledByDefault: true

RubocopRailsAccessibility/ImageHasAlt:
  Enabled: true
  StyleGuide: https://github.com/github/rubocop-rails-accessibility/blob/master/guides/image-has-alt.md
RubocopRailsAccessibility/NoPositiveTabindex:
  Enabled: true
  StyleGuide: https://github.com/github/rubocop-rails-accessibility/blob/master/guides/no-positive-tabindex.md
RubocopRailsAccessibility/NoRedundantImageAlt:
  Enabled: true
  StyleGuide: https://github.com/github/rubocop-rails-accessibility/blob/master/guides/no-redundant-image-alt.md
